version: '3.4'

services:
    feeder:
        container_name: feeder
        image: niradler/feeder
        restart: always
        environment:
            DATABASE_URL: 'postgresql://postgres:${DB_POSTGRESDB_PASSWORD}@postgres:5432/feeder?schema=public'
            JWT_SECRET: '${JWT_SECRET}'
            SESSION_SECRET: '${SESSION_SECRET}'
            FEEDER_PASSWORD: '${FEEDER_PASSWORD}'
            API_KEY: '${API_KEY}'
            NODE_ENV: production
            STATIKLY_CORS_ORIGIN: localhost
            STATIKLY_GLOBAL_HELMET: false
        volumes:
            - ./data:/usr/src/app/prisma/data
        depends_on:
            - postgres
        ports:
            - 3112:3111
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '${DB_POSTGRESDB_PASSWORD}'
        ports:
            - '5432:5432'
    #optional admin panel with directus
    feeder-admin:
        container_name: feeder-admin
        image: directus/directus:latest
        ports:
            - 3113:8055
        depends_on:
            - postgres
        environment:
            KEY: '${directus_key}'
            SECRET: '${directus_secret}'

            DB_CLIENT: 'pg'
            DB_HOST: 'postgres'
            DB_PORT: '5432'
            DB_DATABASE: 'feeder'
            DB_USER: 'postgres'
            DB_PASSWORD: '${DB_POSTGRESDB_PASSWORD}'

            ADMIN_EMAIL: '${ADMIN_EMAIL}'
            ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
