version: '3.4'

services:
    feeder:
        container_name: feeder
        image: niradler/feeder
        restart: always
        environment:
            DATABASE_URL: 'postgresql://postgres:${DB_POSTGRESDB_PASSWORD}@postgres:5432/feeder?schema=public'
            JWT_SECRET: '${JWT_SECRET}'
            SESSION_SECRET: '${SESSION_SECRET}'
            FEEDER_PASSWORD: '${FEEDER_PASSWORD}'
            API_KEY: '${API_KEY}'
            NODE_ENV: production
            STATIKLY_CORS_ORIGIN: localhost
            STATIKLY_GLOBAL_HELMET: false
        volumes:
            - ./data:/usr/src/app/prisma/data
        ports:
            - 3111:3111
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '${DB_POSTGRESDB_PASSWORD}'
        ports:
            - '5432:5432'
